### ISSUE TITLE
errored out during transformation Cannot read property 'constant' of undefined

### ISSUE THREAD

**Issue by adarshmadrecha** [developit/optimize-plugin#14] opened 2020-12-22 07:40 UTC
I am using this plugin in [documentation site](https://help.jamku.app) created using [vuepress ](https://vuepress.vuejs.org/config/#configurewebpack)(Vue based static site generator)

``` js
// .vuepress/config.js

const OptimizePlugin = require('optimize-plugin');
configureWebpack: {
    plugins: [
      new OptimizePlugin({
        downlevel: false,
      })
    ],
  }
```

Error Details
```
errored out during transformation  TypeError: C:\dev\jamkudoc\1.server-bundle.js: Cannot read property 'constant' of undefined
    at PluginPass.FunctionExpression|FunctionDeclaration (C:\dev\jamkudoc\node_modules\babel-preset-modernize\dist\plugins\transform-iife-arrows\index.js:1:424)
    at newFn (C:\dev\jamkudoc\node_modules\optimize-plugin\node_modules\@babel\traverse\lib\visitors.js:175:21)
    at NodePath._call (C:\dev\jamkudoc\node_modules\optimize-plugin\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (C:\dev\jamkudoc\node_modules\optimize-plugin\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (C:\dev\jamkudoc\node_modules\optimize-plugin\node_modules\@babel\traverse\lib\path\context.js:92:31)
    at TraversalContext.visitQueue (C:\dev\jamkudoc\node_modules\optimize-plugin\node_modules\@babel\traverse\lib\context.js:115:16)
    at TraversalContext.visitMultiple (C:\dev\jamkudoc\node_modules\optimize-plugin\node_modules\@babel\traverse\lib\context.js:79:17)
    at TraversalContext.visit (C:\dev\jamkudoc\node_modules\optimize-plugin\node_modules\@babel\traverse\lib\context.js:141:19)
    at Function.traverse.node (C:\dev\jamkudoc\node_modules\optimize-plugin\node_modules\@babel\traverse\lib\index.js:82:17)
    at NodePath.visit (C:\dev\jamkudoc\node_modules\optimize-plugin\node_modules\@babel\traverse\lib\path\context.js:99:18) {
  type: 'TypeError',
  code: 'BABEL_TRANSFORM_ERROR'
```

**Comment by DreierF** [comment] 2021-01-03 17:24
Duplicate of https://github.com/developit/babel-preset-modernize/issues/3

**Comment by developit** [comment] 2022-02-02 15:32
Also duplicate of #7.

**Closed by developit** 2022-02-02 15:32 UTC
Labels: upstream
